CourseDiscussion/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('', include('home.urls'), name='home'),
    path('search/', include('search.urls'), name='search'),
    path('discussion/', include('discussion.urls'), name='discussion'),
    path('users/', include('users.urls'), name='users'),
    path('admin/', admin.site.urls),
    url(r'^captcha/', include('captcha.urls')),
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
]

discussion/urls.py
from django.urls import path
from . import views
from haystack.views import discussionSearchView

app_name = 'discuss'
urlpatterns = [
    path('', views.index, name='index'),
    path('ask/', views.ask_question, name='ask_question'),
    path('tags/<int:id>/', views.tag_questions, name='tag_questions'),
    path('tags/add/', views.add_tag, name='add_tag'),
    path('<int:id>/', views.question_details, name='question_details'),
    path('discussion/search/', discussionSearchView(), name='haystack_search_1'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.homepage, name='homepage')
]

search/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import SearchView

app_name = 'search'
urlpatterns = [
    path('', views.index, name='index'),
    path('course/', SearchView(), name='haystack_search'),
    #path('course/', views.select, name='haystack_search'),
    path('feedback/', views.feedback, name='feedback'),
    path('select/', views.select, name='select'),
]

urls.py
# encoding: utf-8
from django.conf.urls import url

from haystack.views import SearchView

urlpatterns = [
    url(r"^$", SearchView(), name="haystack_search"),
    url(r"^discussion/$", discussionSearchView(), name="haystack_search_1"),
            ]

users/urls.py
from django.urls import re_path, path, include
from django.conf.urls import url
from . import views

app_name = 'users'
urlpatterns = [
    # 登录页面
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('register_1/?name=<name>&email=<email>/', views.register_1, name='register_1'),
    path('process/', views.process, name='process'),
    path('personalpage/', views.personalpage, name='personalpage'),
    path('passwordreset/', views.password_reset, name='password_reset')
]

discussion/models.py
from django.db import models
from users.models import User


class Tag(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Question(models.Model):
    title = models.CharField(max_length=100)
    body = models.CharField(max_length=1000)
    tags = models.ManyToManyField(Tag, related_name='questions', blank=True)
    create_at = models.DateTimeField(auto_now_add=True)
    views = models.PositiveIntegerField(default=0)
    asked_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='questions')

    def __str__(self):
        return self.title

class Answer(models.Model):
    message = models.CharField(max_length=1000)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers')
    create_at = models.DateTimeField(auto_now_add=True)
    create_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='answers')


class Comment(models.Model):
    message = models.CharField(max_length=1000)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, related_name='comments')
    create_at = models.DateTimeField(auto_now_add=True)
    create_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')

search/models.py
from django.db import models


# Create your models here.
class lessons(models.Model):
    """课程的属性"""
    number = models.CharField(max_length=10)  # 课程号
    name = models.CharField(max_length=10)  # 课程名称
    teacher = models.CharField(max_length=5)  # 开课教师
    institute = models.CharField(max_length=20, default="机械与动力工程学院")  # 开课学院
    credit = models.FloatField(default=2.0)  # 学分
    semester = models.CharField(max_length=15, default="2019-2020-2")  # 开课学年
    day = models.IntegerField(default=0)  # 周几上课
    time_started = models.IntegerField(default=0)   #第几节开始
    time_ended = models.IntegerField(default=0)  #第几节结束
    week_started = models.IntegerField(default=0)  # 开始周次
    week_ended = models.IntegerField(default=0)   # 结束周次
    is_interval = models.IntegerField(default=0)   # 是否为单双周，不是为0，单周为1，双周为2
    location = models.CharField(max_length=10, default="上院102")  # 上课地点
    date_added = models.DateTimeField(auto_now_add=True)  # 课程添加时间

    def __str__(self):
        """返回模型地字段表示"""
        return self.name


class feedback(models.Model):
    """反馈"""
    title = models.CharField(max_length=20)  # 标题
    text = models.TextField()  # 内容
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """返回反馈的字段显示"""
        return self.title

discussion/forms.py
from django.forms import ModelForm
from django import forms
from .models import Tag, Question, Answer, Comment


class NewQuestionForm(ModelForm):
    """创建新问题表单"""
    class Meta:
        model = Question
        fields = ['title', 'body', 'tags']
        labels = {'title': '标题', 'body': '问题描述', 'tags': '标签'}
        widgets = {
            'body': forms.Textarea(attrs={'rows': 8, 'placeholder': 'What a question it is?'}),
            'tags': forms.CheckboxSelectMultiple
        }


class NewAnswerForm(ModelForm):
    """回答问题表单"""
    class Meta:
        model = Answer
        fields = ['message']
        widgets = {
            'message': forms.Textarea(attrs={'rows': 8, 'placeholder': 'Edit your answer here'})
        }


class AddCommentForm(ModelForm):
    """评论表单"""
    class Meta:
        model = Comment
        fields = ['message']
        widgets = {
            'message': forms.Textarea(attrs={'rows': 3})
        }


class AddTagForm(ModelForm):
    """添加新标签表单"""
    class Meta:
        model = Tag
        fields = ['name']
        labels = {'name': '标签名'}
        widgets = {
            'name': forms.Textarea(attrs={'rows': 1})
        }

search/forms.py
from django import forms
from .models import feedback


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = feedback
        fields = ['title', 'text']
        labels = {'title': '标题', 'text': '内容'}
        widgets = {'text': forms.Textarea(attrs={'col': 80})}

class SelectTestForm(forms.Form):
    SELVALUE = (
        ('标题', 'first'),
        ('内容', 'second'),
        ('作者', 'third'),
    )
    sel_value = forms.CharField(max_length=10, widget=forms.widgets.Select(choices=SELVALUE))

discussion/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from .models import Tag, Question, Answer, Comment
from .forms import NewQuestionForm, NewAnswerForm, AddCommentForm, AddTagForm
from users.models import User


def index(request):
    """问答主页"""
    new_questions = Question.objects.order_by('-create_at')
    hot_questions = Question.objects.order_by('-views')
    tags = Tag.objects.all()
    return render(request, 'discussion/index.html',
                  {'new_questions': new_questions, 'hot_questions': hot_questions, 'tags': tags})


def tag_questions(request, id):
    """标签下问题列表"""
    tag = get_object_or_404(Tag, id=id)
    questions = tag.questions.order_by('-create_at')
    return render(request, 'discussion/tag_questions.html', {'tag': tag, 'questions': questions})


def question_details(request, id):
    """问题详情页"""
    question = get_object_or_404(Question, id=id)
    question.views += 1
    question.save()
    if request.method == 'POST':
        if request.POST.get("which") == "answer":  # 用户所提交的是回答
            answer_form = NewAnswerForm(request.POST)
            if answer_form.is_valid():
                answer = answer_form.save(commit=False)
                answer.question = question
                answer.create_by = User.objects.get(id=request.session.get('user_id'))
                answer.save()
        elif request.POST.get("which") == "comment":  # 用户所提交的是评论
            comment_form = AddCommentForm(request.POST)
            if comment_form.is_valid():
                answer = get_object_or_404(Answer, id=int(request.POST.get("current_answer")))
                comment = comment_form.save(commit=False)
                comment.answer = answer
                comment.create_by = User.objects.get(id=request.session.get('user_id'))
                comment.save()
        return redirect(reverse('discuss:question_details', kwargs={'id': question.id}))

    else:
        answer_form = NewAnswerForm()
        comment_form = AddCommentForm()
        return render(request, 'discussion/question_details.html',
                      {'question': question, 'answer_form': answer_form, 'comment_form': comment_form})


def ask_question(request):
    """提问"""
    if request.method == 'POST':
        form = NewQuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.asked_by = User.objects.get(id=request.session.get('user_id'))
            question.save()

        return redirect(reverse('discuss:question_details', kwargs={'id': question.id}))

    else:
        form = NewQuestionForm()

        return render(request, 'discussion/ask_question.html', {'form': form})


def add_tag(request):
    """添加新的标签"""
    if request.method == 'POST':
        form = AddTagForm(request.POST)
        if form.is_valid():
            tag = form.save()
            tag.save()
        return redirect(reverse('discuss:index'))
    else:
        form = AddTagForm()
        return render(request, 'discussion/add_tag.html', {'form': form})

search/views.py
from django.shortcuts import render
from .forms import FeedbackForm
from .models import lessons
from haystack.views import SearchView
from django.urls import reverse
from django.http import HttpResponseRedirect


# Create your views here.
def index(request):
    """搜索主页"""
    institute = request.GET.get("institute")
    return render(request, 'search/index.html',institute)


def select(request):
    """筛选过后的结果"""
    institute = request.GET.get("institute")
    context={"institute":institute}
    SearchView(context)
    return render(request,'search/search.html')


def feedback(request):
    """提交反馈"""
    if request.method == 'POST':
        # POST提交的数据，对数据进行处理
        form = FeedbackForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'search/succeed.html')
    else:
        # 未提交数据
        form = FeedbackForm()
        context = {'form': form}
        return render(request, 'search/feedback.html', context)


def show(request):
    """显示筛选页面"""
    list = lessons.objects.all()
    return render(request, 'search/show.html', )

templates/discussion/add_tag.html
{% extends 'discussion/base_discussion.html' %}
{% load widget_tweaks %}
{% block title %}添加标签{% endblock %}

{% block content %}
    <div class="container">
    <form method="post">
    {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
            {{ form.name|add_class:'form-control'  }}
            {% for error in form.name.errors %}
            <span class="help-block">{{ error }}</span>
            {% endfor %}
        </div>
        <div class="form-group">
        <button type="submit" class="btn btn-success">提交</button>
        <a href="{% url 'discuss:index' %}" class="btn btn-light">取消</a>
        </div>
    </form>
    </div>
{% endblock %}

templates/discussion/ask_question.html
{% extends 'discussion/base_discussion.html' %}
{% load widget_tweaks %}
{% block title %}提问{% endblock %}

{% block content %}
    <div class="container">
    {% if request.session.is_login %}
    <form method="post">
    {% csrf_token %}

    <div class="form-group">
        <label for="{{ form.title.id_for_label }}">{{ form.title.label }}</label>
        {{ form.title|add_class:'form-control'  }}
        {% for error in form.title.errors %}
           <span class="help-block">{{ error }}</span>
        {% endfor %}
    </div>
    <div class="form-group">
        <label for="{{ form.body.id_for_label }}">{{ form.body.label }}</label>
        {{ form.body|add_class:'form-control'  }}
        {% for error in form.body.errors %}
           <span class="help-block">{{ error }}</span>
        {% endfor %}
    </div>
    <div class="form-group">
        <label for="{{ form.tags.id_for_label }}">{{ form.tags.label }}</label>
        <small class="text-muted">若无符合的标签，可暂不选择标签 或 <a href={% url 'discuss:add_tag' %}>添加标签</a></small>
        {{ form.tags  }}
        {% for error in form.tags.errors %}
           <span class="help-block">{{ error }}</span>
        {% endfor %}
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-success">提交</button>
        <a href="{% url 'discuss:index' %}" class="btn btn-light">取消</a>
    </div>

    </form>
    {% else %}
    <div class="alert alert-warning" role="alert">
    您尚未登录，无法提问！请先<a href="{% url 'users:login' %}">登录</a>或<a href="{% url 'users:register' %}">注册</a>
    </div>
    {% endif %}
    </div>
{% endblock %}

templates/discussion/base_discussion.html
{% extends 'base.html' %}
{% load static %}

{% block nav-item %}
    <li class="nav-item ">
        <a class="nav-link" href="{% url 'home:homepage' %}">主页</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'search:index' %}">课程</a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" href="{% url 'discuss:index' %}">问答</a>
    </li>
{% endblock %}

templates/discussion/index.html
{% extends 'discussion/base_discussion.html' %}

{% block title %}问答{% endblock %}

{% block stylesheet %}
<style>
    .row{
    margin:10px;
    }
</style>
{% endblock %}

{% block content %}
    <div class="container">
      <div class="row">
        <div class="col-2">
           <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
             <a class="nav-link active" id="v-pills-new-tab" data-toggle="pill" href="#v-pills-new" role="tab" aria-controls="v-pills-new" aria-selected="true">最新问题</a>
             <a class="nav-link" id="v-pills-hot-tab" data-toggle="pill" href="#v-pills-hot" role="tab" aria-controls="v-pills-hot" aria-selected="false">热门问题</a>
             <a class="nav-link" id="v-pills-tag-tab" data-toggle="pill" href="#v-pills-tag" role="tab" aria-controls="v-pills-tag" aria-selected="false">问题分类</a>
           </div>
        </div>
        <div class="col-10">
          <div class="tab-content" id="v-pills-tabContent">
            <div class="tab-pane fade show active" id="v-pills-new" role="tabpanel" aria-labelledby="v-pills-new-tab">
              <div class="container">
                <div class="row">
                <div class="col-8"><h1>New Questions</div>
                <div class="col-4"><a href="{% url 'discuss:ask_question' %}" class="btn btn-outline-primary">Ask Question</a></div>
                </div>
              </div>

            <div class="container">
                <form action="{% url 'discuss:haystack_search_1' %}" method="get">
                <div class="row">
                    <div class="col-8">
                      <input  class="form-control" type="text" name="q" placeholder="请输入关键字">
                    </div>
                    <div class="col-4">
                        <input class="btn btn-light" type="submit" id="discuss" value="搜索">
                    </div>
                </div>
                </form>
            </div>

              <table class="table table-hover">
                <tr>
                  <th>问题</th>
                  <th>回答数</th>
                  <th>浏览量</th>
                </tr>
                {% for question in new_questions %}
                <tr>
                  <td>
                    <a href="{% url 'discuss:question_details' question.id %}">{{ question.title }}</a><br>
                    {% for tag in question.tags.all %}
                    <small><a href="{% url 'discuss:tag_questions' tag.id %}"><span class="badge badge-secondary">{{ tag }}</span></a></small>
                    {% endfor %}
                  </td>
                  <td>{{ question.answers.count }}</td>
                  <td>{{ question.views }}</td>
                </tr>
                {% endfor %}
              </table>
          </div>


            <div class="tab-pane fade" id="v-pills-hot" role="tabpanel" aria-labelledby="v-pills-hot-tab">
              <div class="container">
                <div class="row">
                <div class="col-8"><h1>Top Questions</div>
                <div class="col-4"><a href="{% url 'discuss:ask_question' %}" class="btn btn-outline-primary">Ask Question</a></div>
                </div>
              </div>

            <div class="container">
                <form action="{% url 'discuss:haystack_search_1' %}" method="get">
                <div class="row">
                    <div class="col-8">
                      <input  class="form-control" type="text" name="q" placeholder="请输入关键字">
                    </div>
                    <div class="col-4">
                        <input class="btn btn-light" type="submit" id="discuss" value="搜索">
                    </div>
                </div>
                </form>
            </div>

              <table class="table table-hover">
                <tr>
                  <th>问题</th>
                  <th>回答数</th>
                  <th>浏览量</th>
                </tr>
                {% for question in hot_questions %}
                <tr>
                  <td>
                    <a href="{% url 'discuss:question_details' question.id %}">{{ question.title }}</a><br>
                    {% for tag in question.tags.all %}
                    <small><a href="{% url 'discuss:tag_questions' tag.id %}"><span class="badge badge-secondary">{{ tag }}</span></a></small>
                    {% endfor %}
                  </td>
                  <td>{{ question.answers.count }}</td>
                  <td>{{ question.views }}</td>
                </tr>
                {% endfor %}
              </table>
          </div>

          <div class="tab-pane fade" id="v-pills-tag" role="tabpanel" aria-labelledby="v-pills-tag-tab">
              <div class="container">
                <div class="row">
                <div class="col-8"><h1>标签</h1></div>
                <div class="col-4"><a href="{% url 'discuss:add_tag' %}" class="btn btn-outline-primary">添加标签</a></div>
                </div>
                {% for tag in tags %}
                    <div class="card w-50">
                        <div class="card-header"><a href="{% url 'discuss:tag_questions' tag.id %}">{{ tag.name }}</a></div>
                        <div class="card-body">
                            <p class="card-text">{{ tag.questions.count }} 个问题</p>
                        </div>
                    </div>
                {% endfor %}
              </div>
          </div>

          </div>
      </div>
    </div>

{% endblock %}

templates/discussion/question_details.html
{% extends 'discussion/base_discussion.html' %}
{% load widget_tweaks %}
{% block title %}{{ question.title }}{% endblock %}

{% block content %}
    <div class="container">
    {% if request.session.is_login %}
    <h2>{{ question.title}}</h2>

    <div class="container">
        <div class="row">
            <p class="text-muted">浏览 &nbsp;</p>
            <p>{{ question.views }}</p>
            <p class="text-muted">&nbsp;次</p>
        </div>
    </div>

    <div class="card">
        <div class="card-header">问题描述</div>
        <div class="card-body">
            <div class="col text-left">
            {{ question.body }}
            <div class="col text-right">
                <small class="text-muted">{{ question.asked_by }}</small><br>
                <small class="text-muted">发表于{{ question.create_at }}</small>
            </div>
            </div>
        </div>
        </div>

    <br>
    <h5>{{ question.answers.count }} 个回答</h5>

    {% for answer in question.answers.all %}
        <div class="card">
        <div class="card-body">
            <div class="col text-left">
            {{ answer.message }}
            <div class="col text-right">
                <small class="text-muted">{{ answer.create_by }}</small><br>
                <small class="text-muted">编辑于{{ answer.create_at }}</small>
            </div>
            {% for comment in answer.comments.all %}
                <div class="container">
                <div class="dropdown-divider"></div>
                    <div class="row">
                        <div class="col">
                            <p>{{ comment.message }} </p>
                        </div>
                        <div class="col text-right">
                        <small class="text-muted">{{ comment.create_by }}&nbsp;评论于{{ comment.create_at }}</small>
                        </div>
                    </div>
                </div>

            {% endfor %}
            </div>
            <small>
                <a  data-toggle="collapse" href="#collapseExample{{ answer.id }}" aria-expanded="false">
                    add a comment
                </a>
            </small>

            <div class="collapse" id="collapseExample{{ answer.id }}">
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    {{ comment_form.message|add_class:'form-control' }}
                    <input type="hidden" name="which" value="comment">
                    <input type="hidden" name="current_answer" value="{{ answer.id }}">
                    {% for error in comment_form.message.errors %}
                        <span class="help-block">{{ error }}</span>
                    {% endfor %}
                </div>
                <button type="submit" class="btn btn-outline-success"><small>Comment</small></button>
            </form>
            </div>
        </div>
        </div>
    {% endfor %}
    <br><br>
    <form method="post">
        {% csrf_token %}
        {% for hidden in answer_form.hidden_fields %}
          {{ hidden }}
        {% endfor %}
        
        {% for field in answer_form.visible_fields %}
          <div class="form-group">
            <label for="{{ field.id_for_label }}"><h5>Your Answer</h5></label>
            {{ field|add_class:'form-control' }}
            <input type="hidden" name="which" value="answer">
            {% for error in field.errors %}
               <span class="help-block">{{ error }}</span>
            {% endfor %}
        {% endfor %}
        <button type="submit" class="btn btn-success">提交</button>
    </form>
    {% else %}
    <div class="alert alert-warning" role="alert">
    您尚未登录，无法查看问题详情！请先<a href="{% url 'users:login' %}">登录</a>或<a href="{% url 'users:register' %}">注册</a>
    </div>
    {% endif %}
    </div>
{% endblock %}

templates/discussion/search.html
{% extends 'search/base_search.html' %}

{% block title %}问题列表{% endblock %}
{% load highlight %}

{% block content %}
    <div class="container">
    <div class="col-md-9">
    <div class="row text-center vertical-middle-sm">
        <h1>搜索结果</h1>
    </div>
　　{# 如果存在搜索关键字 #}
    {% if query %}
        {% for result in page.object_list %}<div class="media">
            <a href="{{  result.object.get_absolute_url }}" class="list-group-item active">
                    {% if result.object.avatar %}
                        <div class="media-left">
                            <img src="{{  result.object.avatar.url }}" alt="avatar" style="max-width: 100px; border-radius: 20px">
                        </div>
            {% endif %}
                <div class="media-body">
                    <h4 class="list-group-item-heading">{{ result.object.title }}</h4>
                    <p class="list-group-item-text">{{ result.object.tags }}</p>
                </div>
            </a>
        </div>
            {% empty %}
            <h3>没有找到相关问题</h3>
        {% endfor %}
    {% endif %}

{#        {% include 'paginator.html' %}#}

{#    分页插件，下一页和上一页记得要带上q={{ query }}参数，否则单击下一页时会丢失搜索参数q，而显示出来全部的文章的第二页#}
    <div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?q={{ query }}&page={{ page.previous_page_number }}">上一页</a>
        {% endif %}

        <span class="current">
            Page{{ page.number }} of {{ page.paginator.num_pages }}
        </span>

        {% if page.has_next %}
            <a href="?q={{ query }}&page={{ page.next_page_number }}">下一页</a>
        {% endif %}
    </span>
</div>
    </div>
    </div>
{% endblock %}

templates/discussion/tag_questions.html
{% extends 'discussion/base_discussion.html' %}
{% block title %}{{ tag.name }}{% endblock %}

{% block content %}
    <div class="container">
    <p class="lead">标签 {{ tag.name }} 有 {{ questions.count }} 个问题：</p>
    <table class="table table-hover">
    <tr>
        <th>Question</th>
        <th>Votes</th>
        <th>Answers</th>
        <th>Views</th>
    </tr>
    {% for question in questions %}
        <tr>
            <td>
                <a href="{% url 'discuss:question_details' question.id %}">{{ question.title }}</a>
            </td>
            <td>{{ question.votes }}</td>
            <td>{{ question.answers.count }}</td>
            <td>{{ question.views }}</td>
        </tr>
    {% endfor %}
    </table>
    </div>
{% endblock %}