CourseDiscussion/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('', include('home.urls'), name='home'),
    path('search/', include('search.urls'), name='search'),
    path('discussion/', include('discussion.urls'), name='discussion'),
    path('users/', include('users.urls'), name='users'),
    path('admin/', admin.site.urls),
    url(r'^captcha/', include('captcha.urls')),
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
]

discussion/urls.py
from django.urls import path
from . import views
from haystack.views import discussionSearchView

app_name = 'discuss'
urlpatterns = [
    path('', views.index, name='index'),
    path('ask/', views.ask_question, name='ask_question'),
    path('tags/<int:id>/', views.tag_questions, name='tag_questions'),
    path('tags/add/', views.add_tag, name='add_tag'),
    path('<int:id>/', views.question_details, name='question_details'),
    path('discussion/search/', discussionSearchView(), name='haystack_search_1'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.homepage, name='homepage')
]

search/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import SearchView

app_name = 'search'
urlpatterns = [
    path('', views.index, name='index'),
    path('course/', SearchView(), name='haystack_search'),
    #path('course/', views.select, name='haystack_search'),
    path('feedback/', views.feedback, name='feedback'),
    path('select/', views.select, name='select'),
]

urls.py
# encoding: utf-8
from django.conf.urls import url

from haystack.views import SearchView

urlpatterns = [
    url(r"^$", SearchView(), name="haystack_search"),
    url(r"^discussion/$", discussionSearchView(), name="haystack_search_1"),
            ]

search/models.py
from django.db import models


# Create your models here.
class lessons(models.Model):
    """课程的属性"""
    number = models.CharField(max_length=10)  # 课程号
    name = models.CharField(max_length=10)  # 课程名称
    teacher = models.CharField(max_length=5)  # 开课教师
    institute = models.CharField(max_length=20, default="机械与动力工程学院")  # 开课学院
    credit = models.FloatField(default=2.0)  # 学分
    semester = models.CharField(max_length=15, default="2019-2020-2")  # 开课学年
    day = models.IntegerField(default=0)  # 周几上课
    time_started = models.IntegerField(default=0)   #第几节开始
    time_ended = models.IntegerField(default=0)  #第几节结束
    week_started = models.IntegerField(default=0)  # 开始周次
    week_ended = models.IntegerField(default=0)   # 结束周次
    is_interval = models.IntegerField(default=0)   # 是否为单双周，不是为0，单周为1，双周为2
    location = models.CharField(max_length=10, default="上院102")  # 上课地点
    date_added = models.DateTimeField(auto_now_add=True)  # 课程添加时间

    def __str__(self):
        """返回模型地字段表示"""
        return self.name


class feedback(models.Model):
    """反馈"""
    title = models.CharField(max_length=20)  # 标题
    text = models.TextField()  # 内容
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """返回反馈的字段显示"""
        return self.title

search/forms.py
from django import forms
from .models import feedback


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = feedback
        fields = ['title', 'text']
        labels = {'title': '标题', 'text': '内容'}
        widgets = {'text': forms.Textarea(attrs={'col': 80})}

class SelectTestForm(forms.Form):
    SELVALUE = (
        ('标题', 'first'),
        ('内容', 'second'),
        ('作者', 'third'),
    )
    sel_value = forms.CharField(max_length=10, widget=forms.widgets.Select(choices=SELVALUE))

search/views.py
from django.shortcuts import render
from .forms import FeedbackForm
from .models import lessons
from haystack.views import SearchView
from django.urls import reverse
from django.http import HttpResponseRedirect


# Create your views here.
def index(request):
    """搜索主页"""
    institute = request.GET.get("institute")
    return render(request, 'search/index.html',institute)


def select(request):
    """筛选过后的结果"""
    institute = request.GET.get("institute")
    context={"institute":institute}
    SearchView(context)
    return render(request,'search/search.html')


def feedback(request):
    """提交反馈"""
    if request.method == 'POST':
        # POST提交的数据，对数据进行处理
        form = FeedbackForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'search/succeed.html')
    else:
        # 未提交数据
        form = FeedbackForm()
        context = {'form': form}
        return render(request, 'search/feedback.html', context)


def show(request):
    """显示筛选页面"""
    list = lessons.objects.all()
    return render(request, 'search/show.html', )

templates/search/base_search.html
{% extends 'base.html' %}
{% load static %}

{% block nav-item %}
    <li class="nav-item ">
        <a class="nav-link" href="{% url 'home:homepage' %}">主页</a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" href="{% url 'search:index' %}">课程</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'discuss:index' %}">问答</a>
    </li>
{% endblock %}

templates/search/discussion_search.html
{% extends 'discussion/base_discussion.html' %}

{% block title %}问题列表{% endblock %}
{% load highlight %}

{% block content %}
    <div class="container">
    <div class="col-md-9">
    <div class="row text-center vertical-middle-sm">
        <h1>问题结果</h1>
    </div>
　　{# 如果存在搜索关键字 #}
    {% if query %}
        <table class="table">
            <tr>
                <th>问题</th>
                <th>回答数</th>
                <th>浏览量</th>
            </tr>
            {% for result in page.object_list %}
                <tr>
                  <td>
                    <a href="{% url 'discuss:question_details' result.object.id %}">{{ result.object.title }}</a><br>
                    {% for tag in result.object.tags.all %}
                    <small><a href="{% url 'discuss:tag_questions' tag.id %}"><span class="badge badge-secondary">{{ tag }}</span></a></small>
                    {% endfor %}
                  </td>
                  <td>{{ result.object.answers.count }}</td>
                  <td>{{ result.object.views }}</td>
                </tr>

            {% empty %}
            <h3>没有找到相关问题</h3>
            {% endfor %}
    </table>
    {% endif %}

{#        {% include 'paginator.html' %}#}

{#    分页插件，下一页和上一页记得要带上q={{ query }}参数，否则单击下一页时会丢失搜索参数q，而显示出来全部的文章的第二页#}
    <div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?q={{ query }}&page={{ page.previous_page_number }}">上一页</a>
        {% endif %}

        <span class="current">
            Page{{ page.number }} of {{ page.paginator.num_pages }}
        </span>

        {% if page.has_next %}
            <a href="?q={{ query }}&page={{ page.next_page_number }}">下一页</a>
        {% endif %}
    </span>
</div>
    </div>
    </div>
{% endblock %}

templates/search/feedback.html
{% extends 'search/base_search.html' %}
{% load widget_tweaks %}
{% block title %}反馈{% endblock %}

{% block content %}
    <div class="container">
    <h3 style="margin: 40px">反馈</h3>
    <form method="post">
        {% csrf_token %}

        {% for field in form.visible_fields %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field|add_class:'form-control' }}
        </div>
        {% endfor %}

        <div class="form-group">
          <button type="submit" class="btn btn-success">提交</button>
          <a href="{% url 'search:index' %}" class="btn btn-light">取消</a>
        </div>
    </form>
    </div>
{% endblock content %}

templates/search/index.html
{% extends 'search/base_search.html' %}
{%  load static %}
{% block title %}搜索{% endblock %}

{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/search_style.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
    <div class="row justify-content-center" style="margin-top: 150px">
      <div class="card">
        <div class="card-body">
        <form  action="{% url 'search:haystack_search' %}" method="get">
        <div class="row justify-content-center" style="margin: 40px">
            <div class="search-box">
            <input class="search-txt" type="text" name="q" placeholder="请输入关键字">
            <button class="search-btn">
                <svg class="bi bi-search" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z"/>
                <path fill-rule="evenodd" d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z"/>
                </svg>
            </button>
            </div>
        </div>
        <div class="row">
            <div class="col">
            <div class="form-group">
             <label for="institute">开课学院：</label>
             <select class="form-control" name="institute" id="institute">
                <option value ="请选择">请选择</option>
                {#{% for institute in institutes %}  #}
                 {#<option value ={{ institute }}>{{ institute }}</option>#}
                    {# {% endfor %}#}
                <option value ="电子信息与电气工程学院">电子信息与电气工程学院</option>
                <option value ="机械与动力工程学院">机械与动力工程学院</option>
                <option value ="生物医学工程学院">生物医学工程学院</option>
                <option value ="船舶海洋与建筑工程学院">船舶海洋与建筑工程学院</option>
                <option value ="材料科学工程学院">材料科学与工程学院</option>
            </select>
            </div>
            </div>
            <div class="col">
            <div class="form-group">
             <label for="year">开课学年：</label>
             <select class="form-control" name="year" id="year">
                <option value ="请选择">请选择</option>
                {#{% for institute in institutes %}  #}
                 {#<option value ={{ institute }}>{{ institute }}</option>#}
                    {# {% endfor %}#}
                <option value ="2019-2020-1">2019-2020-1</option>
                <option value ="2019-2020-2">2019-2020-2</option>
                <option value ="2019-2020-3">2019-2020-3</option>
            </select>
            </div>
            </div>
        </div>
        </form>

         没有要找的课程？<a href="{% url 'search:feedback' %} ">点击这里</a>
    </div>
    </div>
    </div>
    </div>

{% endblock %}

templates/search/search.html
{% extends 'search/base_search.html' %}

{% block title %}课程列表{% endblock %}
{% load highlight %}


{% block content %}
    <div class="container">
    <div class="col-md-9">
    <div class="row text-center vertical-middle-sm">
        <h1>搜索结果</h1>
    </div>

　　{# 如果存在搜索关键字 #}
    {% if query %}
        {% for result in page.object_list %}
                <div class="card">
                    <div class="card-header">课程名：{{ result.object.name }}</div>
                    <div class="card-body">
                    <p class="card-text">学分：{{ result.object.credit }}</p>
                    <p class="card-text">教师：{{ result.object.teacher }}</p>
                    <p class="card-text">学院：{{ result.object.institute}}</p>
                    <p class="card-text">开课学年：{{ result.object.semester }}</p>
                    <p class="card-text">上课时间：{{ result.object.time }}</p>
                    <p class="card-text">上课周次：{{ result.object.weeks }}</p>
                    <p class="card-text">上课地点：{{ result.object.location }}</p>
                    </div>
                </div>
        {% empty %}
            <h3>没有找到相关课程</h3>
        {% endfor %}
    {% endif %}

{#        {% include 'paginator.html' %}#}

{#    分页插件，下一页和上一页记得要带上q={{ query }}参数，否则单击下一页时会丢失搜索参数q，而显示出来全部的课程的第二页#}
    <div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?q={{ query }}&page={{ page.previous_page_number }}">上一页</a>
        {% endif %}

        <span class="current">
            Page{{ page.number }} of {{ page.paginator.num_pages }}
        </span>

        {% if page.has_next %}
            <a href="?q={{ query }}&page={{ page.next_page_number }}">下一页</a>
        {% endif %}
    </span>
    <p>
            <a href="{% url 'search:feedback' %} ">反馈</a>
    </p>
</div></div>
    </div>
{% endblock %}

templates/search/sel_test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" action="">
    <select name="sel_value">
        {# 这里我们遍历form表单中的SELVALUE这个字典,然后把key,value成对取出  #}
        {% for key,value in select_form.SELVALUE %}
            <option value="{{ value }}">{{ key }}</option>
        {% endfor %}
    </select>
    <input type="submit" value="测试"/>
    {% csrf_token %}
</form>
</body>
</html>

templates/search/select.html
{% extends 'search/base_search.html' %}

{% block title %}课程列表{% endblock %}
{% load highlight %}


{% block content %}
    <div class="col-md-9">
    <div class="row text-center vertical-middle-sm">
        <h1>搜索结果</h1>
    </div>

　　{# 如果存在搜索关键字 #}
    {% if query %}
        {% for result in page.object_list %}

                <div class="card">
                    <div class="card-header">课程名：{{ result.object.name }}</div>
                    <div class="card-body">
                    <p class="card-text">学分：{{ result.object.credit }}</p>
                    <p class="card-text">教师：{{ result.object.teacher }}</p>
                    <p class="card-text">学院：{{ result.object.institute}}</p>
                    <p class="card-text">开课学年：{{ result.object.semester }}</p>
                    <p class="card-text">上课时间：{{ result.object.time }}</p>
                    <p class="card-text">上课周次：{{ result.object.weeks }}</p>
                    <p class="card-text">上课地点：{{ result.object.location }}</p>
                    </div>
                </div>

            {% empty %}
            <h3>没有找到相关课程</h3>
        {% endfor %}
    {% endif %}

{#        {% include 'paginator.html' %}#}

{#    分页插件，下一页和上一页记得要带上q={{ query }}参数，否则单击下一页时会丢失搜索参数q，而显示出来全部的课程的第二页#}
    <div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?q={{ query }}&page={{ page.previous_page_number }}">上一页</a>
        {% endif %}

        <span class="current">
            Page{{ page.number }} of {{ page.paginator.num_pages }}
        </span>

        {% if page.has_next %}
            <a href="?q={{ query }}&page={{ page.next_page_number }}">下一页</a>
        {% endif %}
    </span>
    <p>
            <a href="{% url 'search:feedback' %} ">反馈</a>
    </p>
</div></div>
{% endblock %}

templates/search/succeed.html
{% extends 'search/base_search.html' %}

{% block title %}Succeed{% endblock %}

{% block content %}
    <p>提交成功</p>
    <p>
        <a href = "{% url 'search:index' %}">返回主页</a>
    </p>
{% endblock %}