CourseDiscussion/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('', include('home.urls'), name='home'),
    path('search/', include('search.urls'), name='search'),
    path('discussion/', include('discussion.urls'), name='discussion'),
    path('users/', include('users.urls'), name='users'),
    path('admin/', admin.site.urls),
    url(r'^captcha/', include('captcha.urls')),
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
]

discussion/urls.py
from django.urls import path
from . import views
from haystack.views import discussionSearchView

app_name = 'discuss'
urlpatterns = [
    path('', views.index, name='index'),
    path('ask/', views.ask_question, name='ask_question'),
    path('tags/<int:id>/', views.tag_questions, name='tag_questions'),
    path('tags/add/', views.add_tag, name='add_tag'),
    path('<int:id>/', views.question_details, name='question_details'),
    path('discussion/search/', discussionSearchView(), name='haystack_search_1'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.homepage, name='homepage')
]

search/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import SearchView

app_name = 'search'
urlpatterns = [
    path('', views.index, name='index'),
    path('course/', SearchView(), name='haystack_search'),
    #path('course/', views.select, name='haystack_search'),
    path('feedback/', views.feedback, name='feedback'),
    path('select/', views.select, name='select'),
]

urls.py
# encoding: utf-8
from django.conf.urls import url

from haystack.views import SearchView

urlpatterns = [
    url(r"^$", SearchView(), name="haystack_search"),
    url(r"^discussion/$", discussionSearchView(), name="haystack_search_1"),
            ]

users/urls.py
from django.urls import re_path, path, include
from django.conf.urls import url
from . import views

app_name = 'users'
urlpatterns = [
    # 登录页面
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('register_1/?name=<name>&email=<email>/', views.register_1, name='register_1'),
    path('process/', views.process, name='process'),
    path('personalpage/', views.personalpage, name='personalpage'),
    path('passwordreset/', views.password_reset, name='password_reset')
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from search.models import lessons
from users.models import User
from discussion.models import Question, Tag


def homepage(request):
    users = User.objects.all()
    lessonlist = lessons.objects.all()
    questions = Question.objects.all()
    tags = Tag.objects.all()
    return render(request, 'home.html', {'users':users, 'lessons': lessonlist, 'questions': questions, 'tags': tags})

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/submit_successfully.js' %}"></script>
  <style>
      .transport{
          font-size: 15px;
          position: fixed;
          bottom: 0px;
          left:400px;
          margin: 5px;
      }
      .transport>ul{
          font-family:"微软雅黑 Light";
      }
      .transport>ul,li{
       list-style: none;
          padding: 0;
          margin: 0;
      }
      .transport>ul>li{
          float: left;
      }
      .transport>ul>li>a{
          text-decoration: none;
          display: block;
          color: #336699;
          padding: 8px 50px;
          border-right:1px solid white;
      }
      .transport>ul>li>a:hover{
          color:white;
          background-color: #A52A2A;
          font-weight: bold;
          border-right:1px solid white;
      }

      .detail>li{
          font-size: 18px;
          font-family: "微软雅黑 Light";
          color: #5897fb;
      }

  </style>
    {% block stylesheet %}{% endblock %}
  </head>

  <body>
    {% block body %}
    <nav class="navbar sticky-top navbar-expand navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'home:homepage' %}">CourseDiscussion</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          {% block nav-item %}
            <li class="nav-item ">
              <a class="nav-link" href="{% url 'home:homepage' %}">主页</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'search:index' %}">课程</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'discuss:index' %}">问答</a>
            </li>
          {% endblock %}
        </ul>



        <div class="btn-group" role="group" aria-label="account">
           {% if not request.session.is_login %}
        <div class="btn-group" role="group" aria-label="account">
          <a class="btn btn-primary" href="{% url 'users:login' %}">登录</a>
          <a class="btn btn-outline-primary" href="{% url 'users:register' %}">注册</a>
        </div>
        {% else %}
        <ul class="navbar-nav navbar-right">
           <li class="nav-item dropdown">
             <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  欢迎！ {{ request.session.user_name |capfirst}}
             </a>
             <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
              <a class="dropdown-item" href="{% url 'users:personalpage' %}">个人主页</a>
                 <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'users:password_reset' %}">修改密码</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'users:logout' %}">注销</a>
             </div>
            </li>
        </ul>
        {% endif %}
        </div>
      </div>
    </nav>

{% block content %}
{% endblock %}

<div class="transport">
<ul>
    <li><a class="transport_index" href="https://www.sjtu.edu.cn" target="_blank">学校官网</a></li>
    <li><a class="transport_oc" href="https://oc.sjtu.edu.cn" target="_blank">Canvas在线平台</a></li>
    <li><a class="transport_i" href="https://i.sjtu.edu.cn" target="_blank">教学信息服务网</a></li>
    <li><a class="transport_box" href="https://jbox.sjtu.edu.cn" target="_blank">交大云盘</a></li>
       </ul>
</div>
    {% endblock body %}
  </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}CourseDiscussion - 主页{% endblock %}

{% block stylesheet %}
<style>
    .jumbotron{
    margin:0;
    }
</style>
{% endblock %}

{% block nav-item %}
    <li class="nav-item ">
        <a class="nav-link active" href="{% url 'home:homepage' %}">主页</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'search:index' %}">课程</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'discuss:index' %}">问答</a>
    </li>
{% endblock %}

{% block content %}
<div id="carousel" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carousel" data-slide-to="0" class="active"></li>
    <li data-target="#carousel" data-slide-to="1"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'img/img3.jpg' %}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>课程信息检索</h5>
        <p>点击顶部菜单栏“课程”，按条件检索课程信息</p>
      </div>
    </div>

    <div class="carousel-item">
      <img src="{% static 'img/read.jpg' %}" class="d-block w-100" alt="..."  height="576px">
      <div class="carousel-caption d-none d-md-block">
        <h5>问答讨论平台</h5>
        <p>点击顶部菜单栏“问答”，看看有哪些感兴趣的问题~</p>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carousel" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carousel" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="jumbotron">
  <h1 class="display-4">欢迎使用本系统!</h1>
  <p class="lead">交大课程信息检索，问答讨论平台</p>
  <hr class="my-4">
  <p>本系统已有：</p>
  <div class="container">
  <div class="row">
     <div class="col">
        <svg class="bi bi-people-fill" width="2em" height="2em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H7zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm-5.784 6A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1h4.216zM4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5z"/>
        </svg>
     <p>{{ users.count }}位用户注册</p>
     </div>
      <div class="col">
        <svg class="bi bi-book-half" width="2em" height="2em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M12.786 1.072C11.188.752 9.084.71 7.646 2.146A.5.5 0 0 0 7.5 2.5v11a.5.5 0 0 0 .854.354c.843-.844 2.115-1.059 3.47-.92 1.344.14 2.66.617 3.452 1.013A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.276-.447L15.5 2.5l.224-.447-.002-.001-.004-.002-.013-.006-.047-.023a12.582 12.582 0 0 0-.799-.34 12.96 12.96 0 0 0-2.073-.609zM15 2.82v9.908c-.846-.343-1.944-.672-3.074-.788-1.143-.118-2.387-.023-3.426.56V2.718c1.063-.929 2.631-.956 4.09-.664A11.956 11.956 0 0 1 15 2.82z"/>
        <path fill-rule="evenodd" d="M3.214 1.072C4.813.752 6.916.71 8.354 2.146A.5.5 0 0 1 8.5 2.5v11a.5.5 0 0 1-.854.354c-.843-.844-2.115-1.059-3.47-.92-1.344.14-2.66.617-3.452 1.013A.5.5 0 0 1 0 13.5v-11a.5.5 0 0 1 .276-.447L.5 2.5l-.224-.447.002-.001.004-.002.013-.006a5.017 5.017 0 0 1 .22-.103 12.958 12.958 0 0 1 2.7-.869z"/>
        </svg>
     <p>{{ lessons.count }}门课程信息</p>
     </div>
     <div class="col">
        <svg class="bi bi-question-circle-fill" width="2em" height="2em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM6.57 6.033H5.25C5.22 4.147 6.68 3.5 8.006 3.5c1.397 0 2.673.73 2.673 2.24 0 1.08-.635 1.594-1.244 2.057-.737.559-1.01.768-1.01 1.486v.355H7.117l-.007-.463c-.038-.927.495-1.498 1.168-1.987.59-.444.965-.736.965-1.371 0-.825-.628-1.168-1.314-1.168-.901 0-1.358.603-1.358 1.384zm1.251 6.443c-.584 0-1.009-.394-1.009-.927 0-.552.425-.94 1.01-.94.609 0 1.028.388 1.028.94 0 .533-.42.927-1.029.927z"/>
        </svg>
     <p>{{ questions.count }}个问题讨论</p>
     </div>
    </div>
    </div>
</div>
{% endblock %}