CourseDiscussion/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('', include('home.urls'), name='home'),
    path('search/', include('search.urls'), name='search'),
    path('discussion/', include('discussion.urls'), name='discussion'),
    path('users/', include('users.urls'), name='users'),
    path('admin/', admin.site.urls),
    url(r'^captcha/', include('captcha.urls')),
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
]

discussion/urls.py
from django.urls import path
from . import views
from haystack.views import discussionSearchView

app_name = 'discuss'
urlpatterns = [
    path('', views.index, name='index'),
    path('ask/', views.ask_question, name='ask_question'),
    path('tags/<int:id>/', views.tag_questions, name='tag_questions'),
    path('tags/add/', views.add_tag, name='add_tag'),
    path('<int:id>/', views.question_details, name='question_details'),
    path('discussion/search/', discussionSearchView(), name='haystack_search_1'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.homepage, name='homepage')
]

urls.py
# encoding: utf-8
from django.conf.urls import url

from haystack.views import SearchView

urlpatterns = [
    url(r"^$", SearchView(), name="haystack_search"),
    url(r"^discussion/$", discussionSearchView(), name="haystack_search_1"),
            ]

users/urls.py
from django.urls import re_path, path, include
from django.conf.urls import url
from . import views

app_name = 'users'
urlpatterns = [
    # 登录页面
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('register_1/?name=<name>&email=<email>/', views.register_1, name='register_1'),
    path('process/', views.process, name='process'),
    path('personalpage/', views.personalpage, name='personalpage'),
    path('passwordreset/', views.password_reset, name='password_reset')
]

users/models.py
from django.db import models
from django import forms
from captcha.fields import CaptchaField


# Create your models here.
class RegisterForm(forms.Form):
    gender = (
        ('male', "男"),
        ('female', "女"),
    )
    institute = (
        ('船院','船舶海洋与建筑工程学院'),
        ('电院', '电子信息与电气工程学院'),
        ('机动', '机械与动力工程学院'),
        ('材料','材料科学与工程学院'),
        ('环境','环境科学与工程学院'),
        ('生医工','生物医学工程学院'),
        ('航空','航空航天学院'),
        ('数学','数学科学学院'),
        ('物理','物理与天文学院'),
        ('化学', '化学化工学院'),
        ('致远','致远学院'),
        ('海洋','海洋学院'),
        ('生命科学','生命科学技术学院'),
        ('农学院','农业与生物学院'),
        ('药学院','药学院'),
        ('医学院', '医学院'),
        ('安泰', '安泰经济与管理学院'),
        ('法学院','凯原法学院'),
        ('外院','外国语学院'),
        ('人文','人文学院'),
        ('马院','马克思主义学院'),
        ('媒体','媒体与传播学院'),
        ('设计','设计学院'),

    )
    username = forms.CharField(label="用户名", max_length=128, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label="密码", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label="确认密码", max_length=256,
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label="邮箱地址", widget=forms.EmailInput(attrs={'class': 'form-control'}))
    sex = forms.ChoiceField(label='性别', choices=gender)
    captcha = CaptchaField(label='验证码')
    institute = forms.ChoiceField(label='学院', choices=institute)

class User(models.Model):
    '''用户表'''
    gender = (
        ('male', '男'),
        ('female', '女'),
    )
    institute=(
        ('船院', '船舶海洋与建筑工程学院'),
        ('电院', '电子信息与电气工程学院'),
        ('机动', '机械与动力工程学院'),
        ('材料', '材料科学与工程学院'),
        ('环境', '环境科学与工程学院'),
        ('生医工', '生物医学工程学院'),
        ('航空', '航空航天学院'),
        ('数学', '数学科学学院'),
        ('物理', '物理与天文学院'),
        ('化学', '化学化工学院'),
        ('致远', '致远学院'),
        ('海洋', '海洋学院'),
        ('生命科学', '生命科学技术学院'),
        ('农学院', '农业与生物学院'),
        ('药学院', '药学院'),
        ('医学院', '医学院'),
        ('安泰', '安泰经济与管理学院'),
        ('法学院', '凯原法学院'),
        ('外院', '外国语学院'),
        ('人文', '人文学院'),
        ('马院', '马克思主义学院'),
        ('媒体', '媒体与传播学院'),
        ('设计', '设计学院'),
    )
    name = models.CharField(max_length=128, unique=True)
    password = models.CharField(max_length=256)
    email = models.EmailField(unique=True)
    sex = models.CharField(max_length=32, choices=gender, default='男')
    c_time = models.DateTimeField(auto_now_add=True)
    mylessons = models.ManyToManyField('search.lessons', related_name='myusers')
    institute = models.CharField( max_length=20,choices=institute,default='电院')
    def __str__(self):
        return self.name

    class Meta:
        ordering = ['c_time']
        verbose_name = '用户'
        verbose_name_plural = '用户'

users/forms.py
from captcha.fields import CaptchaField

from django import forms


class UserForm(forms.Form):
    username = forms.CharField(label="用户名", max_length=128, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label="密码", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    captcha = CaptchaField(label='验证码', error_messages={"invalid": "验证码错误"})


class RegisterForm(forms.Form):
    gender = (
        ('male', "男"),
        ('female', "女"),
    )
    institute = (
        ('电院', '电子信息与电气工程学院'),
        ('船院', '船舶海洋与建筑工程学院'),
        ('机动', '机械与动力工程学院'),
        ('材料', '材料科学与工程学院'),
        ('环境', '环境科学与工程学院'),
        ('生医工', '生物医学工程学院'),
        ('航空', '航空航天学院'),
        ('数学', '数学科学学院'),
        ('物理', '物理与天文学院'),
        ('化学', '化学化工学院'),
        ('致远', '致远学院'),
        ('海洋', '海洋学院'),
        ('生命科学', '生命科学技术学院'),
        ('农学院', '农业与生物学院'),
        ('药学院', '药学院'),
        ('医学院', '医学院'),
        ('安泰', '安泰经济与管理学院'),
        ('法学院', '凯原法学院'),
        ('外院', '外国语学院'),
        ('人文', '人文学院'),
        ('马院', '马克思主义学院'),
        ('媒体', '媒体与传播学院'),
        ('设计', '设计学院'),

    )
    username = forms.CharField(label="用户名", max_length=128, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label="密码", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label="确认密码", max_length=256,
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label="邮箱地址", widget=forms.EmailInput(attrs={'class': 'form-control'}))
    sex = forms.ChoiceField(label='性别', choices=gender)
    captcha = CaptchaField(label='验证码')
    institute = forms.ChoiceField(label='学院', choices=institute)

class PasswordResetForm(forms.Form):
    old_password = forms.CharField(label="旧密码", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password1 = forms.CharField(label="新密码", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password2 = forms.CharField(label="确认新密码", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    captcha = CaptchaField(label='验证码', error_messages={"invalid": "验证码错误"})

users/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from oauth2_provider.views.generic import ProtectedResourceView
from django.http import HttpResponse
from django.contrib.auth import authenticate
from furl import furl
from django.http import HttpResponseRedirect
from .models import User
from .forms import UserForm, RegisterForm, PasswordResetForm
from . import models
import hashlib
import requests
import json


def logout(request):
    """注销账户"""
    if not request.session.get('is_login', None):
        # 如果本来就未登录
        return HttpResponseRedirect(reverse('home:homepage'))
    request.session.flush()
    return HttpResponseRedirect(reverse('home:homepage'))


def register(request):
    """注册新用户"""
    if request.session.get('is_login', None):
        # 登录状态不允许注册
        HttpResponseRedirect(reverse('home:homepage'))
    if request.method == "POST":
        register_form = RegisterForm(request.POST)
        message = "请检查填写的内容！"
        if register_form.is_valid():  # 获取数据
            username = register_form.cleaned_data['username']
            password1 = register_form.cleaned_data['password1']
            password2 = register_form.cleaned_data['password2']
            email = register_form.cleaned_data['email']
            sex = register_form.cleaned_data['sex']
            institute = register_form.cleaned_data['institute']
            if password1 != password2:  # 判断两次密码是否相同
                message = "两次输入的密码不同！"
                return render(request, 'users/register.html', locals())
            else:
                same_name_user = models.User.objects.filter(name=username)
                if same_name_user:  # 用户名唯一
                    message = '用户已经存在，请重新选择用户名！'
                    return render(request, 'users/register.html', locals())
                same_email_user = models.User.objects.filter(email=email)
                if same_email_user:  # 邮箱地址唯一
                    message = '该邮箱地址已被注册，请使用别的邮箱！'
                    return render(request, 'users/register.html', locals())
                # 当一切都OK的情况下，创建新用户
                new_user = models.User.objects.create()
                new_user.name = username
                new_user.password = hash_code(password1)  # 使用加密密码
                new_user.email = email
                new_user.sex = sex
                new_user.institute = institute
                new_user.save()
                return redirect('users:login')  # 自动跳转到登录页面
    register_form = RegisterForm()
    return render(request, 'users/register.html', locals())


def register_1(request, name, email):
    name = name
    email = email
    if request.session.get('is_login', None):
        # 登录状态不允许注册
        HttpResponseRedirect(reverse('home:homepage'))
    if request.method == "POST":
        register_form = RegisterForm(request.POST)
        message = "请检查填写的内容！"
        if register_form.is_valid():
            # 获取数据
            username = name
            password1 = register_form.cleaned_data['password1']
            password2 = register_form.cleaned_data['password2']
            email = email
            sex = register_form.cleaned_data['sex']
            institute = register_form.cleaned_data['institute']
            if password1 != password2:  # 判断两次密码是否相同
                message = "两次输入的密码不同！"
                return redirect(reverse('users:register_1', kwargs={'name': name, 'email': email}))
            else:
                same_name_user = models.User.objects.filter(name=username)
                if same_name_user:  # 用户名唯一
                    message = '用户已经存在，请重新选择用户名！'
                    return redirect(reverse('users:register_1', kwargs={'name': name, 'email': email}))
                same_email_user = models.User.objects.filter(email=email)
                if same_email_user:  # 邮箱地址唯一
                    message = '该邮箱地址已被注册，请使用别的邮箱！'
                    return redirect(reverse('users:register_1', kwargs={'name': name, 'email': email}))

                # 当一切都OK的情况下，创建新用户
                new_user = User.objects.create()
                new_user.name = username
                new_user.password = hash_code(password1)  # 使用加密密码
                new_user.email = email
                new_user.sex = sex
                new_user.institute = institute
                new_user.save()
                user = models.User.objects.get(name=username)
                request.session['is_login'] = True
                request.session['user_id'] = user.id
                request.session['user_name'] = user.name
                return HttpResponseRedirect(reverse('home:homepage'))
    register_form = RegisterForm()
    return render(request, 'users/register_1.html', locals())


def login(request):
    if request.session.get('is_login', None):
        return redirect('home:homepage')

    login_form = UserForm()
    if request.method != 'POST':
        print('1')
    else:
        login_form = UserForm(request.POST)
        message = "请检查填写的内容！"
        if login_form.is_valid():
            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']
            try:
                user = models.User.objects.get(name=username)
                if user.password == hash_code(password):
                    request.session['is_login'] = True
                    request.session['user_id'] = user.id
                    request.session['user_name'] = user.name
                    return HttpResponseRedirect(reverse('home:homepage'))
                else:
                    message = "密码不正确！"
            except:
                message = "用户不存在！"
        return render(request, 'users/login.html', locals())

    return render(request, 'users/login.html', locals())


def process(request):
    f = furl(request.get_full_path())
    code = f.args['code']
    url = 'https://jaccount.sjtu.edu.cn/oauth2/token'
    client_id = 'sPu9ghxQjehvRUzH9SuY'
    client_secret = 'B0163EAEC431290BBA79D53246C861A76D9B51D692B08389'
    grant_type = 'authorization_code'
    redirect_uri = 'http://127.0.0.1:8000/users/process/'
    data = {
        'grant_type': grant_type,
        'code': code,
        'client_id': client_id,
        'client_secret': client_secret,
        'redirect_uri': redirect_uri
    }
    result = requests.post(url, data)
    strResult = json.loads(result.text)
    id_token = strResult['id_token']
    access_token = strResult['access_token']
    headers = {"Authorization": "Bearer {}".format(access_token)}
    url = 'https://api.sjtu.edu.cn/v1/me/profile?access_token=' + access_token
    r = requests.request(url=url, method='GET', headers=headers, timeout=(20, 60))
    entities = json.loads(r.text).get('entities')
    print(entities)
    for item in entities:
        name = item['name']
        email = item['account']
    same_name_user = models.User.objects.filter(name=name)
    if same_name_user:  # 用户名唯一
        user = models.User.objects.get(name=name)
        request.session['is_login'] = True
        request.session['user_id'] = user.id
        request.session['user_name'] = user.name
        return HttpResponseRedirect(reverse('home:homepage'))
        #return HttpResponseRedirect('http://127.0.0.1:8000/users/login/')
    else:
        return redirect(reverse('users:register_1', kwargs={'name': name, 'email': email + '@sjtu.edu.cn'}))


def personalpage(request):
    if not request.session.get('is_login', None):
        # 如果本来未登录,则返回主页
        return HttpResponseRedirect(reverse('home:homepage'))
    user = User.objects.get(id=request.session.get('user_id'))
    context = {'user': user,
               'user_name': user.name,
               'user_email': user.email,
               'user_sex': user.sex,
               'user_institute': user.institute,
               }
    return render(request, 'users/personalpage.html', context)


def hash_code(s, salt='mysite'):
    h = hashlib.sha256()
    s += salt
    h.update(s.encode())  # update方法只接收bytes类型
    return h.hexdigest()


def password_reset(request):
    if not request.session.get('is_login', None):
        return HttpResponseRedirect(reverse('home:homepage'))

    if request.method == "POST":
        form = PasswordResetForm(request.POST)
        if form.is_valid():
            old = form.cleaned_data['old_password']
            new1 = form.cleaned_data['new_password1']
            new2 = form.cleaned_data['new_password2']
            user = User.objects.get(id=request.session.get('user_id'))
            if user.password == hash_code(old):
                if new1 != new2:
                    message = "两次输入的密码不同！"
                    return render(request, 'users/password_reset.html', {'message': message})
                else:
                    user.password = hash_code(new1)
                    user.save()
                    request.session.flush()
                    return redirect(reverse('users:login'))  # 修改密码后重新登录
            else:
                message = "密码不正确！"
                form = PasswordResetForm()
                return render(request, 'users/password_reset.html', {'form': form, 'message': message})

    form = PasswordResetForm()
    return render(request, 'users/password_reset.html', {'form': form})

templates/users/base_accounts.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block body %}
  <div class="container">
    <h1 class="text-center logo my-4">
      <a href="{% url 'home:homepage' %}">CourseDiscussion</a>
    </h1>
    {% block content %}
    {% endblock %}
  </div>
{% endblock %}

templates/users/login.html
{% extends 'users/base_accounts.html' %}
{% load widget_tweaks %}
{% load static %}
{% block title %}登录{% endblock %}

{% block content %}
    <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <form class='form-login' action="" method="post">
              {% if message %}
                  <div class="alert alert-warning">{{ message }}</div>
              {% endif %}
              {% csrf_token %}
              <h2 class="text-center">欢迎登录</h2>
              <a href="https://jaccount.sjtu.edu.cn/oauth2/authorize?client_id=sPu9ghxQjehvRUzH9SuY&response_type=code&redirect_uri=http://127.0.0.1:8000/users/process/" >jaccount登录</a>
              <div class="form-group">
                {{ login_form.username.label_tag }}
                {{ login_form.username}}
              </div>
              <div class="form-group">
                {{ login_form.password.label_tag }}
                {{ login_form.password }}
              </div>
              <div class="form-group">
                  {{ login_form.captcha.errors }}
                  {{ login_form.captcha.label_tag }}
                  {{ login_form.captcha }}
              </div>
              <button type="reset" class="btn btn-default pull-left">重置</button>
              <button type="submit" class="btn btn-primary pull-right">登录</button>
          </form>
        </div>
        <div class="card-footer text-muted text-center">
          暂无账户？ <a href="{% url 'users:register' %}">点击这里注册</a>
        </div>
      </div>
      <div class="text-center py-2">
      </div>
    </div>
  </div>
{% endblock %}

templates/users/password_reset.html
{% extends 'users/base_accounts.html' %}

{% block title %}修改密码{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title text-center">修改密码</h3>
            {% if message %}
               <div class="alert alert-warning">{{ message }}</div>
            {% endif %}
          <form method="post" novalidate>
            {% csrf_token %}
            <div class="form-group">
                {{ form.old_password.label_tag }}
                {{ form.old_password }}
            </div>
              <div class="form-group">
                {{ form.new_password1.label_tag }}
                {{ form.new_password1 }}
            </div>
              <div class="form-group">
                {{ form.new_password2.label_tag }}
                {{ form.new_password2 }}
            </div>
              <div class="form-group">
                {{ form.captcha.label_tag }}
                {{ form.captcha }}
            </div>
            <button type="submit" class="btn btn-primary btn-block">修改密码</button>
          </form>
        </div>
      <div class="card-footer text-muted text-center">
          成功修改密码后将跳转至重新登录页面
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/users/personalpage.html
{% extends 'base.html' %}
{% block title %}个人主页{% endblock %}

{% block content %}
    {% if  request.session.is_login %}
      <div class="container">
      <div class="row">
        <div class="col-2">
           <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
             <a class="nav-link active" data-toggle="pill" href="#detail" role="tab"  aria-selected="true">个人信息</a>
             <a class="nav-link" data-toggle="pill" href="#courses" role="tab"  aria-selected="false">我的课程</a>
             <a class="nav-link" data-toggle="pill" href="#discuss" role="tab" aria-selected="false">问答记录</a>
           </div>
        </div>
        <div class="col-10">
          <div class="tab-content" id="v-pills-tabContent">
            <div class="tab-pane fade show active" id="detail" role="tabpanel">
        <ul class="detail">
        <li class="username">用户名：{{ user_name}}</li>
        <li class="sex">性别：{{ user_sex }}</li>
        <li class="email">电子邮箱：{{ user_email }}</li>
        <li class="institute">学院：{{ user_institute }}</li>
        </ul>
            </div>
        <div class="tab-pane fade" id="courses" role="tabpanel" aria-labelledby="v-pills-new-tab">
        </div>
        <div class="tab-pane fade" id="discuss" role="tabpanel" aria-labelledby="v-pills-new-tab">
        <h5>我提出的问题</h5>
        <table class="table table-hover">
                <tr>
                  <th>问题</th>
                  <th>提问时间</th>
                  <th>回答数</th>
                </tr>
                {% for question in user.questions.all %}
                <tr>
                  <td>
                    <a href="{% url 'discuss:question_details' question.id %}">{{ question.title }}</a><br>
                    {% for tag in question.tags.all %}
                    <small><a href="{% url 'discuss:tag_questions' tag.id %}"><span class="badge badge-secondary">{{ tag }}</span></a></small>
                    {% endfor %}
                  </td>
                  <td>{{ question.create_at }}</td>
                  <td>{{ question.answers.count }}</td>
                </tr>
                {% endfor %}
              </table>
        <h5>我回答或评论过的问题</h5>
        <table class="table table-hover">
                <tr>
                  <th>问题</th>
                  <th>回答/评论时间</th>
                </tr>
                {% for answer in user.answers.all %}
                <tr>
                  <td>
                    <a href="{% url 'discuss:question_details' answer.question.id %}">{{ answer.question.title }}</a><br>
                    {% for tag in answer.question.tags.all %}
                    <small><a href="{% url 'discuss:tag_questions' tag.id %}"><span class="badge badge-secondary">{{ tag }}</span></a></small>
                    {% endfor %}
                  </td>
                  <td>{{ answer.create_at }}</td>
                </tr>
                {% endfor %}
                {% for comment in user.comments.all %}
                <tr>
                  <td>
                    <a href="{% url 'discuss:question_details' comment.answer.question.id %}">{{ comment.answer.question.title }}</a><br>
                    {% for tag in comment.answer.question.tags.all %}
                    <small><a href="{% url 'discuss:tag_questions' tag.id %}"><span class="badge badge-secondary">{{ tag }}</span></a></small>
                    {% endfor %}
                  </td>
                  <td>{{ comment.create_at }}</td>
                </tr>
                {% endfor %}
              </table>
    {% endif %}
{% endblock %}

templates/users/register.html
{% extends 'users/base_accounts.html' %}

{% block title %}注册{% endblock %}
{% block content %}
    <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <form class='form-register' action="/users/register/" method="post">
              {% if message %}
                  <div class="alert alert-warning">{{ message }}</div>
              {% endif %}
              {% csrf_token %}
              <h2 class="text-center">欢迎注册</h2>
              <div class="form-group">
                  {{ register_form.username.label_tag }}
                  {{ register_form.username}}
              </div>
              <div class="form-group">
                  {{ register_form.password1.label_tag }}
                  {{ register_form.password1 }}
              </div>
              <div class="form-group">
                  {{ register_form.password2.label_tag }}
                  {{ register_form.password2 }}
              </div>
              <div class="form-group">
                  {{ register_form.email.label_tag }}
                  {{ register_form.email }}
              </div>
              <div class="form-group">
                  {{ register_form.sex.label_tag }}
                  {{ register_form.sex }}
              </div>
              <div class="form-group">
                  {{ register_form.institute.label_tag }}
                  {{ register_form.institute }}
              </div>
              <div class="form-group">
                  {{ register_form.captcha.errors }}
                  {{ register_form.captcha.label_tag }}
                  {{ register_form.captcha }}
              </div>
              <button type="reset" class="btn btn-default pull-left">重置</button>
              <button type="submit" class="btn btn-primary pull-right">提交</button>
          </form>
        </div>
        <div class="card-footer text-muted text-center">
          已有账户？ <a href="{% url 'users:login' %}">点击登录</a>
        </div>
      </div>
      <div class="text-center py-2">
      </div>
    </div>
  </div>
{% endblock %}

templates/users/register_1.html
{% extends 'users/base_accounts.html' %}

{% block title %}完善信息{% endblock %}
{% block content %}
    <div class="row justify-content-center">
        <div class="col-lg-4 col-md-6 col-sm-8">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% if message %}
                            <div class="alert alert-warning">{{ message }}</div>
                        {% endif %}
                        {% csrf_token %}
                        <h2 class="text-center">完善信息</h2>
                        <div class="form-group">
                            {{ register_form.username.label_tag }}
                            <input type="text" name="username" class="form-control" maxlength="128" required id="id_username" value="{{ name }}">
                        </div>
                        <div class="form-group">
                            {{ register_form.password1.label_tag }}
                            {{ register_form.password1 }}
                        </div>
                        <div class="form-group">
                            {{ register_form.password2.label_tag }}
                            {{ register_form.password2 }}
                        </div>
                        <div class="form-group">
                            {{ register_form.email.label_tag }}
                            <input type="email" name="email" class="form-control" required id="id_email" value="{{ email }}">
                        </div>
                        <div class="form-group">
                            {{ register_form.sex.label_tag }}
                            {{ register_form.sex }}
                        </div>
                        <div class="form-group">
                            {{ register_form.institute.label_tag }}
                            {{ register_form.institute }}
                        </div>
                        <div class="form-group">
                            {{ register_form.captcha.errors }}
                            {{ register_form.captcha.label_tag }}
                            {{ register_form.captcha }}
                        </div>
                        <button type="reset" class="btn btn-default pull-left">重置</button>
                        <button type="submit" class="btn btn-primary pull-right">提交</button>
                    </form>
                </div>
            </div>
            <div class="text-center py-2">
            </div>
        </div>
    </div>
{% endblock %}